/* prettier-ignore-start */
/* eslint-disable */
// This file is auto-generated by TanStack Router
import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as ProjectIdImport } from "./routes/project.$id";

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const ProjectIdRoute = ProjectIdImport.update({
  id: "/project/$id",
  path: "/project/$id",
  getParentRoute: () => rootRoute,
} as any);

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/project/$id": {
      preLoaderRoute: typeof ProjectIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

export const routeTree = rootRoute.addChildren([IndexRoute, ProjectIdRoute]);
/* prettier-ignore-end */
